// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clear_cache
void clear_cache();
RcppExport SEXP _bfg_clear_cache() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_cache();
    return R_NilValue;
END_RCPP
}
// prepare_cache
void prepare_cache(Rcpp::NumericMatrix X);
RcppExport SEXP _bfg_prepare_cache(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    prepare_cache(X);
    return R_NilValue;
END_RCPP
}
// sample_f_hypers
Rcpp::List sample_f_hypers(Eigen::MatrixXd X, const Eigen::MatrixXd& Qt, const Eigen::VectorXd& Dt, const Eigen::MatrixXd& F, const Eigen::VectorXd& gamma, double tau0_prime_in, double nugget_in, double ell_in, const Eigen::VectorXd& q_val, const Eigen::VectorXd& mass_matrix_diag, double epsilon, int L, const double& slab_scale, const double& slab_df, const int& nu_local, const int& nu_global);
RcppExport SEXP _bfg_sample_f_hypers(SEXP XSEXP, SEXP QtSEXP, SEXP DtSEXP, SEXP FSEXP, SEXP gammaSEXP, SEXP tau0_prime_inSEXP, SEXP nugget_inSEXP, SEXP ell_inSEXP, SEXP q_valSEXP, SEXP mass_matrix_diagSEXP, SEXP epsilonSEXP, SEXP LSEXP, SEXP slab_scaleSEXP, SEXP slab_dfSEXP, SEXP nu_localSEXP, SEXP nu_globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Qt(QtSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type tau0_prime_in(tau0_prime_inSEXP);
    Rcpp::traits::input_parameter< double >::type nugget_in(nugget_inSEXP);
    Rcpp::traits::input_parameter< double >::type ell_in(ell_inSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type q_val(q_valSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mass_matrix_diag(mass_matrix_diagSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double& >::type slab_scale(slab_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type slab_df(slab_dfSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu_local(nu_localSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu_global(nu_globalSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_f_hypers(X, Qt, Dt, F, gamma, tau0_prime_in, nugget_in, ell_in, q_val, mass_matrix_diag, epsilon, L, slab_scale, slab_df, nu_local, nu_global));
    return rcpp_result_gen;
END_RCPP
}
// sample_z_hypers
Rcpp::List sample_z_hypers(const Eigen::MatrixXd& Qt, const Eigen::VectorXd& Dt, const Eigen::MatrixXd& Z, const double& temperature, double nugget_in, double eta, double beta_a, double beta_b, double dir_a, const Eigen::VectorXd& q_val, const Eigen::VectorXd& mass_matrix_diag, double epsilon, int L);
RcppExport SEXP _bfg_sample_z_hypers(SEXP QtSEXP, SEXP DtSEXP, SEXP ZSEXP, SEXP temperatureSEXP, SEXP nugget_inSEXP, SEXP etaSEXP, SEXP beta_aSEXP, SEXP beta_bSEXP, SEXP dir_aSEXP, SEXP q_valSEXP, SEXP mass_matrix_diagSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Qt(QtSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const double& >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type nugget_in(nugget_inSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type beta_a(beta_aSEXP);
    Rcpp::traits::input_parameter< double >::type beta_b(beta_bSEXP);
    Rcpp::traits::input_parameter< double >::type dir_a(dir_aSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type q_val(q_valSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mass_matrix_diag(mass_matrix_diagSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_z_hypers(Qt, Dt, Z, temperature, nugget_in, eta, beta_a, beta_b, dir_a, q_val, mass_matrix_diag, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// sample_f_hypers_SKIM
Rcpp::List sample_f_hypers_SKIM(Eigen::MatrixXd X, const Eigen::MatrixXd& Qt, const Eigen::VectorXd& Dt, const Eigen::MatrixXd& F, double tau0_prime_in, double nugget_in, double ell_in, const Eigen::VectorXd& q_val, const Eigen::VectorXd& mass_matrix_diag, double epsilon, int L, const double& slab_scale, const double& slab_df, const int& nu_local, const int& nu_global);
RcppExport SEXP _bfg_sample_f_hypers_SKIM(SEXP XSEXP, SEXP QtSEXP, SEXP DtSEXP, SEXP FSEXP, SEXP tau0_prime_inSEXP, SEXP nugget_inSEXP, SEXP ell_inSEXP, SEXP q_valSEXP, SEXP mass_matrix_diagSEXP, SEXP epsilonSEXP, SEXP LSEXP, SEXP slab_scaleSEXP, SEXP slab_dfSEXP, SEXP nu_localSEXP, SEXP nu_globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Qt(QtSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type F(FSEXP);
    Rcpp::traits::input_parameter< double >::type tau0_prime_in(tau0_prime_inSEXP);
    Rcpp::traits::input_parameter< double >::type nugget_in(nugget_inSEXP);
    Rcpp::traits::input_parameter< double >::type ell_in(ell_inSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type q_val(q_valSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mass_matrix_diag(mass_matrix_diagSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double& >::type slab_scale(slab_scaleSEXP);
    Rcpp::traits::input_parameter< const double& >::type slab_df(slab_dfSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu_local(nu_localSEXP);
    Rcpp::traits::input_parameter< const int& >::type nu_global(nu_globalSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_f_hypers_SKIM(X, Qt, Dt, F, tau0_prime_in, nugget_in, ell_in, q_val, mass_matrix_diag, epsilon, L, slab_scale, slab_df, nu_local, nu_global));
    return rcpp_result_gen;
END_RCPP
}
// sample_t_hypers
Rcpp::List sample_t_hypers(Eigen::MatrixXd t_distances, const Eigen::MatrixXd& Qy, const Eigen::VectorXd& Dy, const Eigen::MatrixXd& Y, const Eigen::VectorXd& q_val, const double& temperature, const Eigen::VectorXd& mass_matrix_diag, double epsilon, int L, const double& eta, const double& beta_sigma_a, const double& beta_sigma_b, const double& inv_gamma_ell_a, const double& inv_gamma_ell_b);
RcppExport SEXP _bfg_sample_t_hypers(SEXP t_distancesSEXP, SEXP QySEXP, SEXP DySEXP, SEXP YSEXP, SEXP q_valSEXP, SEXP temperatureSEXP, SEXP mass_matrix_diagSEXP, SEXP epsilonSEXP, SEXP LSEXP, SEXP etaSEXP, SEXP beta_sigma_aSEXP, SEXP beta_sigma_bSEXP, SEXP inv_gamma_ell_aSEXP, SEXP inv_gamma_ell_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type t_distances(t_distancesSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Qy(QySEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type q_val(q_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mass_matrix_diag(mass_matrix_diagSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_sigma_a(beta_sigma_aSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_sigma_b(beta_sigma_bSEXP);
    Rcpp::traits::input_parameter< const double& >::type inv_gamma_ell_a(inv_gamma_ell_aSEXP);
    Rcpp::traits::input_parameter< const double& >::type inv_gamma_ell_b(inv_gamma_ell_bSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_t_hypers(t_distances, Qy, Dy, Y, q_val, temperature, mass_matrix_diag, epsilon, L, eta, beta_sigma_a, beta_sigma_b, inv_gamma_ell_a, inv_gamma_ell_b));
    return rcpp_result_gen;
END_RCPP
}
// sample_Z_hypers_and_noise
Rcpp::List sample_Z_hypers_and_noise(const Eigen::MatrixXd& Qt, const Eigen::VectorXd& Dt, const Eigen::MatrixXd& Y, const Eigen::VectorXd& q_val, const double& temperature, const Eigen::VectorXd& mass_matrix_diag, double epsilon, int L, const double& eta, const double& beta_gamma_a, const double& beta_gamma_b, const double& dir_a, const double& beta_sigma_a, const double& beta_sigma_b);
RcppExport SEXP _bfg_sample_Z_hypers_and_noise(SEXP QtSEXP, SEXP DtSEXP, SEXP YSEXP, SEXP q_valSEXP, SEXP temperatureSEXP, SEXP mass_matrix_diagSEXP, SEXP epsilonSEXP, SEXP LSEXP, SEXP etaSEXP, SEXP beta_gamma_aSEXP, SEXP beta_gamma_bSEXP, SEXP dir_aSEXP, SEXP beta_sigma_aSEXP, SEXP beta_sigma_bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Qt(QtSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Dt(DtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type q_val(q_valSEXP);
    Rcpp::traits::input_parameter< const double& >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type mass_matrix_diag(mass_matrix_diagSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_gamma_a(beta_gamma_aSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_gamma_b(beta_gamma_bSEXP);
    Rcpp::traits::input_parameter< const double& >::type dir_a(dir_aSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_sigma_a(beta_sigma_aSEXP);
    Rcpp::traits::input_parameter< const double& >::type beta_sigma_b(beta_sigma_bSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Z_hypers_and_noise(Qt, Dt, Y, q_val, temperature, mass_matrix_diag, epsilon, L, eta, beta_gamma_a, beta_gamma_b, dir_a, beta_sigma_a, beta_sigma_b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bfg_clear_cache", (DL_FUNC) &_bfg_clear_cache, 0},
    {"_bfg_prepare_cache", (DL_FUNC) &_bfg_prepare_cache, 1},
    {"_bfg_sample_f_hypers", (DL_FUNC) &_bfg_sample_f_hypers, 16},
    {"_bfg_sample_z_hypers", (DL_FUNC) &_bfg_sample_z_hypers, 13},
    {"_bfg_sample_f_hypers_SKIM", (DL_FUNC) &_bfg_sample_f_hypers_SKIM, 15},
    {"_bfg_sample_t_hypers", (DL_FUNC) &_bfg_sample_t_hypers, 14},
    {"_bfg_sample_Z_hypers_and_noise", (DL_FUNC) &_bfg_sample_Z_hypers_and_noise, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_bfg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
